### ISSUE TITLE
Incorrect HTML code in README.html

### ISSUE THREAD

**Issue by Diacod-I** [ModelDBRepository/187473#1]
1) The Hyperlink to the website seems to be written incorrectly in the README<br>
![Screenshot 2024-10-01 172658](https://github.com/user-attachments/assets/da39476f-acb1-4a2d-a9ae-7cb16ff10db9)
<br>
2) The website itself cannot be accessed through the given URL and throws a connection error. Either a resolution or an alternative link like the <a href="https://www.neuron.yale.edu/neuron/docs/">new NEURON documentation</a> is needed
<br><br>
3) Images at the end aren't rendered<br><br>

![Screenshot 2024-10-01 181937](https://github.com/user-attachments/assets/5a184239-8f95-46fb-a1ab-a725ed87edce)

**Comment by ramcdougal** [comment]
Thanks for this and for your pull request. We've updated it on the [ModelDB site](https://modeldb.science/187473).

I believe everything is fixed now, and it looks better since it has a markdown readme, so I'm going to close this issue. Please feel free to reopen if there are more changes needed.

**Comment by Diacod-I** [comment]
Sure, I'll look for any necessary changes to be done. I also noticed the changes, such as the changelog.

Looking to contribute as much as I can to reviewing/making models in ModelDB. 👍
